add database
ihiwblby/java-filmorate pull request #3
Opened 2024-11-07 19:38 UTC by ihiwblby

2024-11-08 07:42 UTC, z8q requested changes

2024-11-08 07:42 UTC, z8q commented on pom.xml
>  			<artifactId>logbook-spring-boot-starter</artifactId>
В классе GenreRowMapper.java есть неиспользуемый импорт
org.springframework.beans.factory.annotation.Qualifier

checks на него ругается

2024-11-09 15:54 UTC, ihiwblby commented
Привет! В итоге переделала очень много всего, хочу оставить несколько пояснений:

- решила убрать BaseRepository, не совсем поняла по ТЗ, требовался он или нет. Но показалось, что без него намного лаконичнее и понятнее

- от аннотации qualifier отказалась намеренно, тк исчезла необходимость в классе BaseRepository

- в классе MpaRatingRepository может возникнуть вопрос по поводу метода checkMpaRating. У него немного странная логика, которую можно было бы упростить, но сейчас всё в таком виде из-за тестов постмана. Если рейтинга не существует, и запрос был сделан по пути mpa/id, должна быть ошибка 404. Если несуществующий mpa передается при создании фильма, требуют ошибку 400.

2024-11-10 18:39 UTC, z8q approved these changes

2024-11-10 18:39 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserStorage.java
> +@Component
Тут аннотацию можно не использовать

2024-11-10 19:14 UTC, merged